In [16]:
import numpy as np
from sympy import *

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

Определитель $detA$ второго порядка,  матрицы $A$ определяется как

$$detA=|A|=\begin{vmatrix}
a_{11} & a_{12}\\ 
a_{21} & a_{22}
\end{vmatrix}=a_{11}a_{22} - a_{12}a_{21}.$$

$$detA=\vert A\vert=\begin{vmatrix}sinx&-cosx\\cosx&sinx\end{vmatrix}=sinx\times sinx+cosx\times cosx={sinx}^2+{cosx}^2=1.$$

In [17]:
x = symbols("x")
M = Matrix([[sin(x), -cos(x)], [cos(x), sin(x)]])
a = M.det()

print(f'Матрица:\n{M}')
print(f'Определитель:\n{a}')
print(f'Определитель:\n{simplify(a)}')


Матрица:
Matrix([[sin(x), -cos(x)], [cos(x), sin(x)]])
Определитель:
sin(x)**2 + cos(x)**2
Определитель:
1


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

а) Согласно свойству матриц, для двух квадратных матриц одинакового размера $det(AB)=detA\cdot detB.$ Следовательно 
$$det(A^2)=det(AA)\;=\;det(A)det(A)=4\times4=16$$

б) Согласно свойству матриц, определитель транспонированной матрицы равен определителю исходной. Откуда $det(A^{T})=4$

в) Согласно свойству матриц, умножение строки или столбца матрицы на число  𝜆  приведет к умножению определителя матрицы на то же число. Следовательно 
$$det(2A)=2\times4=8$$

   
__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

По определеию, матрица называется _сингулярной_, или _вырожденной_, если ее определитель равен нулю.

Вычислим определитель заданной матрицы.

$\begin{pmatrix}-2&7&-3\\4&-14&6\\-3&7&13\end{pmatrix}=-2\begin{vmatrix}-14&6\\7&13\end{vmatrix}-7\begin{vmatrix}4&6\\-3&13\end{vmatrix}-3\begin{vmatrix}4&-14\\-3&7\end{vmatrix}=-2\cdot(-14\cdot13-7\cdot6)-7\cdot(4\cdot13+3\cdot6)-3\cdot(4\cdot7-14\cdot3)=448-490+42=0$

Матрица является вырожденной.

In [27]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель:
0


__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [28]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
r = np.linalg.matrix_rank(a)
print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


In [ ]:
4е задание еще буду даделовать